name: Golang Docker Build

on: push
# LET THE PIPELINE TRIGGER ON A PUSH TO ALL BRANCHES

env:
  CONTAINER_REPOSITORY: quay.io/Miel-DR2003 # PUT YOUR OWN USERNAME HERE
  CONTAINER_IMAGE: alm-workshop
  GOLANG_VERSION: 1.23

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Quay.io login
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: user-mhg+workshoprobot
          password: Y0JI87T4ZO63FIT8LMAT5YG26BF2HIMBAQGF290N0G3KQ6VTIL2W3UU8NOILTS4U

      - name: Extract metadata (tags, labels) for Docker
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: quay.io/user-mhg/alm-workshop

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
